import 'dotenv/config';
import * as specAgentAnalyzer from '../src/agents/spec-agent/analyzer';
import * as specAgentPlanner from '../src/agents/spec-agent/planner';
import * as specAgentExecutor from '../src/agents/spec-agent/executor';
import * as codeAgentAnalyzer from '../src/agents/code-agent/analyzer';
import * as codeAgentPlanner from '../src/agents/code-agent/planner';
import * as codeAgentExecutor from '../src/agents/code-agent/executor';
import * as docsAgentAnalyzer from '../src/agents/docs-agent/analyzer';
import * as docsAgentPlanner from '../src/agents/docs-agent/planner';
import * as docsAgentExecutor from '../src/agents/docs-agent/executor';
import { exec } from 'child_process';
import * as fs from 'fs/promises';

async function main() {
  const roundId = parseInt(process.argv[2], 10);
  if (isNaN(roundId)) {
    console.error('Invalid round ID');
    process.exit(1);
  }

  const specAnalysis = await specAgentAnalyzer.analyzeTask('project_tasks.yaml', roundId);
  const specPlan = specAgentPlanner.plan(roundId);
  const prompt = specAgentExecutor.execute(specPlan, specAnalysis);

  const codeAnalysis = codeAgentAnalyzer.analyze(prompt);
  const codePlan = codeAgentPlanner.plan(codeAnalysis);
  const content = await codeAgentExecutor.execute(codePlan);

  let outputPath: string;
  let commitMessage: string;

  if (roundId === 1) {
    outputPath = 'README.md';
    commitMessage = 'docs: Initial README.md generated by Docs Agent for AutoDev AI Hub';
  } else if (roundId === 2) {
    outputPath = 'TECH_STACK.md';
    commitMessage = 'docs: Generated TECH_STACK.md with initial tech stack design for AutoDev AI Hub by Docs Agent';
  } else if (roundId === 3) {
    outputPath = 'ui-wires/dashboard_wireframe.md';
    commitMessage = 'feat: Generated initial UI wireframes for AutoDev AI Hub dashboard by Code/Docs Agents';
  } else {
    console.error(`Round ${roundId} is not supported yet.`);
    process.exit(1);
  }

  const docsAnalysis = docsAgentAnalyzer.analyze(outputPath, content);
  const docsPlan = docsAgentPlanner.plan(docsAnalysis);
  await docsAgentExecutor.execute(docsPlan);

  console.log('Committing and pushing changes...');
  exec(`git add ${outputPath} && git commit -m "${commitMessage}" && git push`, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error during git operations: ${error}`);
      return;
    }
    console.log(stdout);
    console.error(stderr);
  });
}

main().catch(error => {
  console.error('An unexpected error occurred:', error);
  process.exit(1);
});
