import 'dotenv/config';
import { generateProjectBrief } from '../src/agents/specificationModule';
import { writeDocumentation } from '../src/agents/docsAgent';
import { callLLM } from '../src/backend/services/llmService';
import storage from 'node-persist';
import { exec } from 'child_process';

async function main() {
  const roundId = parseInt(process.argv[2], 10);
  if (isNaN(roundId)) {
    console.error('Invalid round ID');
    process.exit(1);
  }

  await storage.init({ dir: 'config' });
  const modelId = await storage.getItem('defaultModel') || 'gemini-1.5-flash';

  console.log(`Generating project brief for round ${roundId}...`);
  const prompt = await generateProjectBrief('project_tasks.yaml', roundId);

  console.log(`Calling LLM with model ${modelId}...`);
  const content = await callLLM(modelId, prompt);

  console.log('Writing documentation...');
  await writeDocumentation('README.md', content);

  console.log('Committing and pushing changes...');
  exec('git add README.md && git commit -m "docs: Initial README.md generated by Docs Agent for AutoDev AI Hub" && git push', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error during git operations: ${error}`);
      return;
    }
    console.log(stdout);
    console.error(stderr);
  });
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
