import 'dotenv/config';
import { generateProjectBrief, generateTechStackPrompt } from '../src/agents/specificationModule';
import { writeDocumentation } from '../src/agents/docsAgent';
import { callLLM } from '../src/backend/services/llmService';
import storage from 'node-persist';
import { exec } from 'child_process';

async function main() {
  const roundId = parseInt(process.argv[2], 10);
  if (isNaN(roundId)) {
    console.error('Invalid round ID');
    process.exit(1);
  }

  await storage.init({ dir: 'config' });
  const modelId = await storage.getItem('defaultModel') || 'gemini-1.5-flash';

  let prompt: string;
  let outputPath: string;
  let commitMessage: string;

  if (roundId === 1) {
    console.log(`Generating project brief for round ${roundId}...`);
    prompt = await generateProjectBrief('project_tasks.yaml', roundId);
    outputPath = 'README.md';
    commitMessage = 'docs: Initial README.md generated by Docs Agent for AutoDev AI Hub';
  } else if (roundId === 2) {
    console.log(`Generating tech stack prompt for round ${roundId}...`);
    prompt = await generateTechStackPrompt('project_tasks.yaml', roundId);
    outputPath = 'TECH_STACK.md';
    commitMessage = 'docs: Generated TECH_STACK.md with initial tech stack design for AutoDev AI Hub by Docs Agent';
  } else {
    console.error(`Round ${roundId} is not supported yet.`);
    process.exit(1);
  }

  console.log(`Calling LLM with model ${modelId}...`);
  const content = await callLLM(modelId, prompt);

  console.log(`Writing documentation to ${outputPath}...`);
  await writeDocumentation(outputPath, content);

  console.log('Committing and pushing changes...');
  exec(`git add ${outputPath} && git commit -m "${commitMessage}" && git push`, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error during git operations: ${error}`);
      return;
    }
    console.log(stdout);
    console.error(stderr);
  });
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
